import { Request, Response } from "express";
import { supabase } from "../config/supabaseClient";

export const saveSpace = async (req: Request, res: Response) => {
  try {
    // 1. We now extract 'id' from the body as well
    const { id, floor_id, name, type, capacity, coordinates } = req.body;

    // 2. Use UPSERT instead of INSERT
    // If 'id' matches an existing row, it updates it.
    // If 'id' is new (or generated by frontend), it inserts it.
    const { data, error } = await supabase
      .from('spaces')
      .upsert([{
        id,
        floor_id,
        name,
        type,
        capacity,
        coordinates
      }])
      .select();

    if (error) throw error;

    res.json(data[0]);
  } catch (error: any) {
    console.error('Error saving space:', error.message);
    res.status(400).json({ error: error.message });
  }
};

export const getSpaces = async (req: Request, res: Response) => {
  try {
    const { floor_id } = req.query;

    if (!floor_id) {
      return res.status(400).json({ error: "Floor ID is required" });
    }

    const { data, error } = await supabase
      .from("spaces")
      .select("*")
      .eq("floor_id", floor_id);

    if (error) throw error;
    res.json(data);
  } catch (error: any) {
    console.error("Error fetching spaces:", error.message);
    res.status(500).json({ error: error.message });
  }
};

export const updateSpace = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { name, type, capacity } = req.body;

    const { data, error } = await supabase
      .from("spaces")
      .update({ name, type, capacity })
      .eq("id", id)
      .select();

    if (error) throw error;
    res.json(data[0]);
  } catch (error: unknown) {
    // Strict error handling without 'any'
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error("Error updating space:", message);
    res.status(400).json({ error: message });
  }
};

export const deleteSpace = async (req: Request, res: Response) => {
  try {
    const { id } = req.params;

    // First, delete bookings associated with this space (Cascade)
    await supabase.from('bookings').delete().eq('space_id', id);

    // Then delete the space
    const { error } = await supabase.from('spaces').delete().eq('id', id);

    if (error) throw error;
    res.json({ message: "Space deleted" });
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
};

export const getAllSpacesGlobal = async (req: Request, res: Response) => {
  try {
    // Join with floors to know where the room is
    const { data, error } = await supabase
      .from('spaces')
      .select('*, floors(name)')
      .order('name');

    if (error) throw error;
    res.json(data);
  } catch (error: any) {
    res.status(500).json({ error: error.message });
  }
};